export const LocalData = {
  resumeTemplates: [
    {
      name: "Divided1",
      source: "/template/template1.png",
      type: "free",
    },
    {
      name: "Divided2",
      source: "/template/template2.png",
      type: "free",
    },
    {
      name: "Divided3",
      source: "/template/template3.webp",
      type: "premium",
    },
    {
      name: "Clean",
      source: "/template/template4.png",
      type: "premium",
    },
    {
      name: "Amsterdam",
      source: "/template/amsterdam-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Dublin",
      source: "/template/dublin-resume-templates.avif",
      type: "premium",
    },
    {
      name: "London",
      source: "/template/london-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Madrid",
      source: "/template/madrid-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Moscow",
      source: "/template/moscow-resume-templates.avif",
      type: "premium",
    },
    {
      name: "New york",
      source: "/template/new-york-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Oslo",
      source: "/template/oslo-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Paris",
      source: "/template/paris-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Santiago",
      source: "/template/santiago-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Singapore",
      source: "/template/singapore-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Stockholm",
      source: "/template/stockholm-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Sydney",
      source: "/template/sydney-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Toronto",
      source: "/template/toronto-resume-templates.avif",
      type: "premium",
    },
    {
      name: "Vienna",
      source: "/template/vienna-resume-templates.avif",
      type: "premium",
    },


  ],

  backgroundColors: [
    "#1C1C1C",
    "#2D2D2D",
    "#3B3B3B",
    "#4A4A4A",
    "#3E2723",
    "#4A235A",
    "#2C3E50",
    "#1C2833",
    "#3B3B48",
    "#2F2F2F",
    "#37474F",
    "#4E4B3A",
    "#1A4D2E",
    "#4E342E",
    "#6A1B9A",
    "#34495E",
    "#1B1B2A",
    "#263238",
    "#3E4A59",
    "#212121",
    "#212F3D",
    "#FF5733",
    "#33FF57",
    "#3357FF",
    "#FF33A1",
    "#A133FF",
    "#33FFA1",
    "#FF7133",
    "#71FF33",
    "#7133FF",
    "#FF3371",
    "#33FF71",
    "#3371FF",
    "#A1FF33",
    "#33A1FF",
    "#FF5733",
    "#5733FF",
    "#33FF5A",
    "#5A33FF",
    "#FF335A",
    "#335AFF",
  ],

  textColors: [
    "#1C1C1C",
    "#2D2D2D",
    "#3B3B3B",
    "#4A4A4A",
    "#4A235A",
    "#3E2723",
    "#3B3B48",
    "#2C3E50",
    "#1C2833",
    "#1A4D2E",
    "#6A1B9A",
    "#4E342E",
    "#5D4037",
    "#34495E",
    "#556070",
    "#3E4A59",
    "#3F51B5",
    "#1B1B2A",
    "#37474F",
    "#4E4B3A",
    "#2F2F2F",
  ],

  sampleResumeInfo: {
    id:"",
    profileData: {
      name: "Jane Doe",
      jobTitle: "Full Stack Engineer",
      description: "Short pitch about yourself.",
      email: "janedoe@gmail.com",
      phone: "+254710617776",
      website: "https://janedoe.com",
      twitter: "twitter.com/JaneDoe",
      linkedin: "linkedin.com/in/JaneDoe",
      instagram: "instagram.com/in/JaneDoe",
      github: "github.com/JaneDoe",
      behance: "behance.com/JaneDoe",
    },
    educationData: [
      {
        degree: "Bsc Computer Technology",
        university: "MIT University",
        startDate: "08/2020",
        endDate: "12/2024",
        city: "",
        courses: "",
      },
    ],
    workExperienceData: [
      {
        jobTitle: "Software Developer",
        companyName: "Uzapoint Limited",
        dates: "04/2023 - 05/2023",
        location: "Nairobi, Kenya",
        companyDesc:
          "Digital Vision is a company dealing with provision of web/mobile based solutions, content applications and technological innovation.",
        achievements:
          "Collaborated with a team of 3 developers to create a finances budget tracking mobile app.Fixed bugs on a client’s (Chamasoft) investment group mobile app.Created end-to-end Figma designs for a tenant mobile app for the company’s clients.",
        present: false,
      },
      {
        jobTitle: "Software Developer",
        companyName: "Uzapoint Limited",
        dates: "04/2023 - 05/2023",
        location: "Nairobi, Kenya",
        companyDesc:
          "Digital Vision is a company dealing with provision of web/mobile based solutions, content applications and technological innovation.",
        achievements:
          "Collaborated with a team of 3 developers to create a finances budget tracking mobile app.Fixed bugs on a client’s (Chamasoft) investment group mobile app.Created end-to-end Figma designs for a tenant mobile app for the company’s clients.",
        present: false,
      },
    ],
    achievementsData: [
      {
        title: "Nairobi Innovation Week Winner (2023)",
        dates: "05/2023 - 05/2023",
        description:
          "Led a team of 3 developers to create a web app that connects skilled artisans to clients in need of household services. The team came in 3rd place in NIW.",
        present: false,
      },
      {
        title: "GDSC Web Developer Lead (Maseno University)",
        dates: "06/2021 - 07/2022",
        description:
          "Mentored and inspired over 120 fellow tech students through consistent weekly sessions.",
        present: false,
      },
    ],
    skillsData: [
      "React JS",
      "Next.JS",
      "Java",
      "Jenkins",
      "Git",
      "AngularJS",
      "Ajax",
      "Node JS",
      "Next JS",
      "React Native",
      "Mongo DB",
      "Spring-boot",
      "C#",
      ".NET",
      "Tailwind CSS",
      "Laravel",
      "Typescript",
      "MySql",
      "Linux",
      "Jira",
      "Python",
    ],
    projectsData: [
      {
        title: "HustleHub",
        dates: "04/2023 - 05/2023",
        link: "https://github.com/DevJane/HustleHubClient",
        description:
          "Led a team of 3 developers to create a React JS web app that connects skilled artisans to clients in need of household services. Implemented user authentication and authorization functionalities, leveraging redux for state management and react router for seamless navigation between different components and routes. Integrated identity verification API (Fal.lu), ensuring a secure and trustworthy platform for both artisans and clients. Employed Redux Thunk middleware to handle asynchronous operations such as API calls, enabling seamless data retrieval and updates.",
        present: false,
      },
      {
        title: "Restaurant Advisor",
        dates: "04/2022 - 04/2022",
        link: "https://github.com/DevJane/restaurants",
        description:
          "Developed a React.js web application with an intuitive user interface, allowing users to search for restaurants based on various criteria, such as location, cuisine, and ratings. Utilized React.js components, state management, and routing to create a smooth and seamless user experience. Integrated external APIs and databases to retrieve and display relevant restaurant data.",
        present: false,
      },
      {
        title: "Movers API",
        dates: "08/2021 - 08/2021",
        link: "https://github.com/DevJane/MoversAPI",
        description:
          "Led a team of 6 developers to successfully build an app for an application that allows users to find moving companies around their areas to help with their relocation. Created and managed our API and databases using Java (Java Spark) and Postgres. Integrated our REST API to app frontend.",
        present: false,
      },
    ],
    certificatesData: [
      {
        title: "Web Applications Development",
        dates: "",
        present: false,
        organization: "Moringa School",
      },
      {
        title: "Android Mobile Applications Development",
        dates: "",
        present: false,
        organization: "Moringa School",
      },
      {
        title: "DevOps Engineering",
        dates: "",
        present: false,
        organization: "Moringa School",
      },
    ],
    interestsData: ["Mountaineering", "Board games", "Sculpting"],
    settings: {
      themeColor: "#4287f5",
    },
  },
};
